/*
 * Copyright (c) 2015-2016, Arkadiusz Materek (arekmat@poczta.fm)
 *
 * Licensed under GNU General Public License 3.0 or later.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef DALI_COMMANDS_DT8_HPP_
#define DALI_COMMANDS_DT8_HPP_

#include <stdint.h>

namespace dali {

enum class CommandDT8 {
  SET_TEMPORARY_X_COORDINATE_WORD = 224,
  SET_TEMPORARY_Y_COORDINATE_WORD = 225,
  ACTIVATE = 226,
  X_COORDINATE_STEP_UP = 227,
  X_COORDINATE_STEP_DOWN = 228,
  Y_COORDINATE_STEP_UP = 229,
  Y_COORDINATE_STEP_DOWN = 230,
  SET_TEMPORARY_COLOUR_TEMPERATURE = 231,
  COLOUR_TEMPERATURE_STEP_COOLER = 232,
  COLOUR_TEMPERATURE_STEP_WARMER = 233,
  SET_TEMPORARY_PRIMARY_N_DIMLEVEL = 234,
  SET_TEMPORARY_RGB_DIMLEVEL = 235,
  SET_TEMPORARY_WAF_DIMLEVEL = 236,
  SET_TEMPORARY_RGBWAF_CONTROL = 237,
  COPY_REPORT_TO_TEMPORARY = 238,

  STORE_TY_PRIMARY_N = 240,
  STORE_XY_COORDINATE_PRIMARY_N = 241,
  STORE_COLOUR_TEMPERATURE_LIMIT = 242,
  STORE_GEAR_FEATURES_STATUS = 243,

  ASSIGN_COLOUR_TO_LINKED_CHANNEL = 245,
  START_AUTO_CALIBRATION = 246,
  QUERY_GEAR_FEATURES_STATUS = 247,
  QUERY_COLOUR_STATUS = 248,
  QUERY_COLOUR_TYPE_FEATURES = 249,
  QUERY_COLOUR_VALUE = 250,
  QUERY_RGBWAF_CONTROL = 251,
  QUERY_ASSIGNED_COLOUR = 252,

  QUERY_EXTENDED_VERSION_NUMBER = 255,
};

}
// namespace dali

#endif // DALI_COMMANDS_DT8_HPP_
